### ISSUE TITLE
Recently-opened books sync again

### ISSUE THREAD

**Issue by ostraat** [hadynz/obsidian-kindle-plugin#107]
The 3 books I have opened on my Kindle in the last 24 hours keep syncing every time I run the sync.  No changes are actually made to the files.

When I deleted one of the files and ran the sync again, I noticed the 'lastAnnotatedDate' front matter field had changed to today's date of '2021-11-15'.  This seems odd since that book in particular has not been opened today (though it would be '2021-11-15' in UTC).

Let me know if there are any more details that would be useful.  Thanks!

**Comment by hadynz** [comment]
The plugin now supports the concept of "resync". It will detect any books that have been accessed since it last synced and will look for any new highlights that might have been made. 

![image](https://user-images.githubusercontent.com/315585/141815359-cfe59d52-dcb1-4103-aeb1-391ac65b87e8.jpeg)

If the "last accessed date" for a book has changed for any reason and is ahead or on the same day of the last sync date, then the plugin will attempt to resync this book just in case there was new highlights added to them. 

The side effect of this is that the plugins might unnecessarily look for highlights when there is none. But how else will the plugin know of any changes?

**Comment by ostraat** [comment]
Ah, that makes sense.  The resync feature is quite useful.

Thank you for the explanation!
