### ISSUE TITLE
lastAnnotatedDate is invalid (Amazon Japan)

### ISSUE THREAD

**Issue by jelomu** [hadynz/obsidian-kindle-plugin#108]
Hi, I am running into issue with version 1.3.1, lastAnnotedDate seems to be invalid

All my book notes have this in their YAML front matter block:
`lastAnnotatedDate: Invalid date`

I use Amazon Japan.

**Comment by hadynz** [comment]
Can you login to https://read.amazon.co.jp/notebook and send me a screenshot of any book that you have?

The plugin has made a strong assumption that all dates will be present as shown in the following screenshot:

![image](https://user-images.githubusercontent.com/315585/141812409-b7ed2632-b556-4a7c-ab71-81dc83daf3d3.jpeg)

**Comment by jelomu** [comment]
That's probably it, the Japanese version of this page is a mix of English and Japanese.
The date is shown in Japanese:

<img width="404" alt="CleanShot 2021-11-16 at 09 35 15@2x" src="https://user-images.githubusercontent.com/94373198/141874675-9d6c4492-291d-44f8-ac88-1686034fde38.png">

Here is the text version:
`Last accessed on 2021年11月15日 月曜日`

So basically: YYYY年MM月DD日 weekday.

**Comment by jelomu** [comment]
Just in case, here's how the highlights are formatted on Amazon Japan:

<img width="847" alt="CleanShot 2021-11-16 at 10 10 38@2x" src="https://user-images.githubusercontent.com/94373198/141877568-8d70f62f-3a67-483a-9915-c82c615d0436.png">

{{ color }} is empty for me so I assume you might be looking for English color names.

If that is the case, here is the list of colors in Japanese:

- 黄色のハイライト = Yellow highlight
- ピンク色のハイライト = Pink highlight
- 青色のハイライト = Blue highlight
- オレンジ色のハイライト = Orange highlight

As a user, I wouldn't mind having these displayed in Japanese in my notes.

One final note, next to the highlight color, after the pipe, the page number is being displayed (ex: `ページ: 134`), but it doesn't seem to be an issue. The location number is correctly synced and works with the desktop Kindle app. It doesn't seem to work with the iOS  Kindle app but I guess that's another topic.

Cheers!

**Comment by hadynz** [comment]
@jelomu thanks for all the information that you've shared and the screenshot. It has really helped me.

I've found a way to solve the colors without adding too much complexity. Rather than looking for the words "yellow" or "黄色のハイライト" to identify colors, I instead now look at CSS tags that represent those colors. I am quite confident that they will all be in English regardless of the Amazon country being used. 

I am hoping we can do something similar with the "Last annotated date" and avoiding going down the path of trying to parse dates in different locales.

Can I kindly ask you to inspect the DOM for books in the left hand side navigation menu and confirm if the date specified in the hidden field is in English or Japanese please?

![Screen Shot 2021-11-16 at 11 21 29 PM](https://user-images.githubusercontent.com/315585/141967768-dd223eef-a36e-4711-92f2-2a643975a9b3.png)

**Comment by hadynz** [comment]
I have fixed the issue with color in version [1.4.0][1]. Would be great if you can confirm for me if that works correctly at your end.

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/1.4.0

**Comment by jelomu** [comment]
I confirm the color issue is fixed and works for all shades!

Regarding the date, here is a screenshot of the DOM. 
The value of the hidden input is in Japanese, same as the one displayed.
<img width="822" alt="Screen Shot 2021-11-16 at 22 06 34" src="https://user-images.githubusercontent.com/94373198/141991627-0f5250bc-cd01-4176-bc04-41fadd2c0272.png">

**Comment by hadynz** [comment]
@jelomu can you try out the latest version 1.5.2. I've added support to parsing Japanese dates.

**Comment by jelomu** [comment]
@hadynz works like a charm!
Thank you for this!!
