### ISSUE TITLE
Date Variable

### ISSUE THREAD

**Issue by eleanorkonik** [hadynz/obsidian-kindle-plugin#11]
Is there a way to have a {{date}} variable for when the book was written/published? That would be really helpful! Thank you :)

**Comment by hadynz** [comment]
The current plugin works by either (a) scraping the [AWS Kindle Reader][1] site, or (b) uploading your `My Clippings.txt` file from your Kindle.

When using method A, the site does not provide any extra information about any of the books. So one option to achieve what you are asking for is to enrich the data gathered by getting more book metadata using the book's [ASIN number][2] which is most certainly available.

When using method B, there is very limited information about the book, document or article. The only chance that is there is to try and search online based on the limited information available (document title, and sometimes author if available), and then going to trying to get more book metadata.

This is for sure a non-trivial enhancement for the plugin. It could be something that I can look to add when using method A, as the required information get more book metadata is consistently available.

Just out of curiosity - what is the use case or value of having the written/published date available along with any notes?

I've considered getting any "tags" metadata that might be associated with a book being very useful to include to build better connections between notes that a user might be unknowingly making through the choice of books they have.

I won't close this issue and will keep track on interest from other users on this request, and consider it after the plugin stabilises and matures.

[1]: https://read.amazon.com/notebook
[2]: https://en.wikipedia.org/wiki/Amazon_Standard_Identification_Number

**Comment by eleanorkonik** [comment]
Oh gosh! I didn't realize it would be so hard -- Amazon definitely has the published date, heh, I didn't know it was stored so differently than the rest. 

My use case is that it takes helps to know how old my information is (i.e. if a book I took notes on is from 2007 or 1997 or 2017 there's a different level of follow up I need to do to make sure the information is still accurate). Most of what I do involves archaeology, and new digs and research can change things a lot, unlike, say, if I were taking notes about philosophy or American history. 

Feel free to close the issue and thanks for the response!

**Comment by hadynz** [comment]
I've implemented your feature request as part of release [0.2.0][1].

Would be great if you can give it a spin and provide any feedback.

Since you've already installed a previous version of the plugin before, and have already synced some books, you will need to:

1. Delete all or some previously synced book(s)
2. Update the Nunjucks template that your plugin is using. Easiest way is to copy the [latest plugin template here][2] and then customise it as you need 
3. Re-run sync (using Amazon sync only)

I've updated the [README file][3] with more extensive information about the available variables that you can use in your template.

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/0.2.0
[2]: https://github.com/hadynz/obsidian-kindle-plugin/blob/master/src/assets/defaultTemplate.njk
[3]: https://github.com/hadynz/obsidian-kindle-plugin/blob/master/README.md

**Comment by hadynz** [comment]
Closing this issue as it has been built and shipped. Feel free to open another issue if you find any bugs with it, and if you have any new feature requests!
