### ISSUE TITLE
Not all highlights get added from manual clippings.txt sync

### ISSUE THREAD

**Issue by tjex** [hadynz/obsidian-kindle-plugin#117]
Added my highlights manually for the first time via clippings.txt (I had never done any other sync, manual or Amazon).
It only imported one highlight out of many. These are highlights from a pdf.
They are present in the clippings.txt file. 

Kindle Highlights v1.4.1
Obsidian v0.12.19

**Comment by hadynz** [comment]
Can you share your my clippings file please?

**Comment by TillmanJex** [comment]
[My Clippings.txt](https://github.com/hadynz/obsidian-kindle-plugin/files/7586299/My.Clippings.txt)

**Comment by hadynz** [comment]
![image](https://user-images.githubusercontent.com/315585/143216103-ccabbb45-4c1f-4a61-9a52-9acf2f1d3be1.png)

Can you try and use the latest version? I just loaded your file without any issues. 

Version 1.4.1 should also work for this file too, which makes this an interesting problem.

**Comment by JoaquinAldoney** [comment]
I have the same problem. Syncing via Amazon results in the same problem. If I try to open it in, let's say, clippings.io, it works just fine. I'll attach my clippings file in case it helps. Btw, thank you a lot for the pluggin! 
[My Clippings.txt](https://github.com/hadynz/obsidian-kindle-plugin/files/7596563/My.Clippings.txt)

**Comment by TillmanJex** [comment]
Thanks for getting back about this. 
I got the same amount of books / highlights too. 
But if you compare the imported clippings for the book New Dark Age in Obsidian / clippings.txt, you'll see that there are many that do not get imported.

**Comment by hadynz** [comment]
> But if you compare the imported clippings for the book New Dark Age in Obsidian / clippings.txt, you'll see that there are many that do not get imported.

@TillmanJex can you share a specific example of a particular quote that exists in your My Clippings.txt file but is missing from the final import by the plugin?

**Comment by TillmanJex** [comment]
I uninstalled and reinstalled the kindle plugin and tried again. 
First time, it only synced 4 books, then the second and third time it synced 5 books. 
For some reason it hasn't synced New Dark Age at all now, which is a PDF and is the only PDF I have highlights in.
See screenshots. 

![Screenshot 2021-11-30 at 09 45 53](https://user-images.githubusercontent.com/83029642/144015079-59091cc1-d5fe-400b-9c1e-dd58d7cbb0f3.png)

![Screenshot 2021-11-30 at 09 47 09](https://user-images.githubusercontent.com/83029642/144015088-b3ecc38d-57b8-4e8b-b7a6-dd6124450fdb.png)
![Screenshot 2021-11-30 at 09 46 43](https://user-images.githubusercontent.com/83029642/144015100-df5a0f84-56df-4b71-bf55-b87d4374435d.pn
![Screenshot 2021-11-30 at 09 46 55](https://user-images.githubusercontent.com/83029642/144015111-81c9f122-0657-4b87-b8a0-8630ea631277.png)
g)

![Screenshot 2021-11-30 at 09 47 09](https://user-images.githubusercontent.com/83029642/144015280-ca81c2a2-5030-4b77-b2bd-a436aee33001.png)
![Screenshot 2021-11-30 at 09 51 02](https://user-images.githubusercontent.com/83029642/144015296-364a5337-41f6-4ca2-81be-6d26fe3396a5.png)

**Comment by hadynz** [comment]
Apologies for the delay in reply. 

@TillmanJex looking at your My Clippings file, I can definitely see a number of issues.

**Missing author name**
Your book or PDF "New Dark Age - James Bridle" does not follow the common convention expected which is "Book or Article title (Author)". Because of that, the plugin has no way to determine who the author of this PDF is. 

From your screenshots, I believe you are using `{{ author }}` as the filename to use. Because no valid author can be determined for this PDF, no file is being printed out. You can work around this issue by using another template name that doesn't use the author.

**Missing highlights**
I can see that there are missing highlights for "New Dark Age" even after I sync it without using the author name. You mentioned that this is not a book, but a PDF. So it is possible that the plugin is not handling annotations for a PDF incorrectly. The My Clippings file is a propriety format created by Amazon that is not documented. So it is not uncommon that users report new use cases that this plugin was designed for. 

This is a valid bug, and I can make a fix for it.

**Wrong books synced counter**
When I choose for book titles to be used as the name of files, I can see that the plugin correctly syncs 6 books. However, the counter is showing is 5. It is possible that this is related to the fact that one of your PDF's "does not have an author" from the plugin's perspective.

This is another valid bug, that I can also make a fix for it.

> First time, it only synced 4 books, then the second and third time it synced 5 books.

With all of the above, I still don't quite understand why you are seeing this behaviour. Nevertheless, I'll work in the next week on making the above fixes and you can try it all again to see if you are seeing this behaviour again or not.

**Comment by TillmanJex** [comment]
Ok, amazing. Thanks so much! And good to know about the {{author}} reference.
Looking forward to the update very much! Coffee on the way!
