### ISSUE TITLE
*** Bring in Articles *** 

### ISSUE THREAD

**Issue by tedblizzard100** [hadynz/obsidian-kindle-plugin#160]
[[Please Request Articals]] 
It looks like the app only works for books and not articles sent to the Kindle.   Please, Is there any way to have the process also sync article highlights? 

I know all the metadata might not be available but it would be super helpful as I spend most of the day in front of a computer. I'm trying to use the Kindle to Obsidian process to save my eyes and read/highlight on the kindle. 

Thank you so much!

**Comment by hadynz** [comment]
You should be able to extract highlights for any type of content (books, articles, PDFs, etc) if you plug in your Kindle to your computer and sync the "My Clippings" file that is on the device.

Syncing using Amazon will only sync content that you buy from Amazon – which is almost exclusively books.

**Comment by tedblizzard100** [comment]
Thank you so much @hadynz.  Is it recommended to use both sync from the kindle and "Syncing using Amazon" or is it only necessary to sync from the kindle via the "My Clippings" file?

**Comment by hadynz** [comment]
You can use either method that you think works for you best. In fact you can also use them both in tandem. 

If you read content that is not purchased from Amazon, then you must sync using My Clippings. 

If you read congdng that is always purchased from Amazon, then you might find syncing from the cloud much more convenient. Also because syncing from the cloud brings in rich metadata, the plugin is able to enrich your highlights with more info about a book - eg publisher, book cover, etc
