### ISSUE TITLE
[BUG] Book titles with non-filename-safe characters are cut off.

### ISSUE THREAD

**Issue by evitiello** [hadynz/obsidian-kindle-plugin#175]
### Describe the bug
When the title of a book has a character in it that isn't allowed by the filesystem, only the first word is used as the filename.

Example: "Summary: Sapiens: A Brief History of Humankind" is created with a filename of "Summary"

### Method of syncing
- [X] Amazon Kindle Reader
- [ ] My Clippings file (please **attach file** that can be used to recreate issue)

### Expected behaviour
the filename should be something like "Summary Sapiens A Brief History of Humankind". or bad characters should be replaced with something good such as "Summary- Sapiens- A Brief History of Humankind

### Metadata
 - OS: Can repeat the results on Mac and iOS.
 - Plugin version: 1.6.3
 - Obsidian version: 0.15.6

**Comment by hadynz** [comment]
Thanks for raising this. You are running into an issue with the "smarts" that's been built in the plugin to truncate long book titles in a meaningful way (regardless if it has invalid characters not allowed by the file system).

The main use case is managing books with a colon. For the following examples, the plugin behaves as follows:

| Original book title                                                         | Shortened title     |
|-----------------------------------------------------------------------------|---------------------|
| The Four Agreements: A Practical Guide to Personal Freedom (A Toltec Wisdom | The Four Agreements |
| The Manager's Path: A Guide for Tech Leaders Navigating Growth and Change   | The Manager's Path  |

It's because of the above reason, that in your example `Summary: Sapiens: A Brief history of humankind` that it gets reduced to `Summary` which is not very helpful.

I'll make a fix to cater for this scenario. In your example, the short name of the book will be `Summary: Sapiens`.

**Comment by evitiello** [comment]
Would it be possible to have a configuration option to disable the truncation altogether?

**Comment by hadynz** [comment]
> Would it be possible to have a configuration option to disable the truncation altogether?

You should be able to use `{{longTitle}}` as a variable for the "file name template"

![image](https://user-images.githubusercontent.com/315585/188336510-a5503a5a-be0e-40ad-9689-16df1d3d3e4f.png)

![image](https://user-images.githubusercontent.com/315585/188336516-6edeb20c-25ec-4ef2-b96f-b57fc40b994c.png)

**Comment by hadynz** [comment]
This has now been fixed in [1.6.9][1].

Can you try it out and let me know if this fix or the previous solution I suggested have helped you achieve what you wanted?

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/1.6.9

**Comment by evitiello** [comment]
Much better, thank you!!
