### ISSUE TITLE
Remove data collection

### ISSUE THREAD

**Issue by joethei** [hadynz/obsidian-kindle-plugin#235]
Hi @hadynz
We (the Obsidian team) noticed that the Kindle plugin has client-side telemetry code posting user data to Sentry from within Obsidian directly.
We are still drafting a privacy and data collection policy for plugins, but there are a few guidelines we have already agreed on.
Mainly, plugins should not submit user data to third-party telemetry services from directly within Obsidian, even if the data collection is opt-in.

Client-side libraries like Sentry's make it too easy for user data unrelated to your plugin to get collected.
We therefore ask you to remove the data collection from this plugin.

**Comment by joethei** [comment]
Hi here,

As we haven't heard from you in almost a month, we have delisted this plugin temporarily.
You can let us know in this issue once you have removed the telemetry and we can relist the plugin.

**Comment by AlexandreCassagne** [comment]
@joethei I applaud your team for resisting the incessant of developers urge to collect endless data from users. Big credibility booster!

**Comment by hadynz** [comment]
Thanks for raising this to my attention @joethei. I've been transitioning to a new job since the start of the year and haven't had a chance to keep a close eye on this project.

Sentry tracking was originally added to help me proactively identify performance and functional bugs with the plugin. 

I love the new mandate to protect data and privacy of all users. I do hope that you can create an interface though that helps developers track the performance of this applications without exposing any user data.

I've removed Sentry in v1.9.0 and the plugin should be completely free of any data collection.

**Comment by joethei** [comment]
Thank you, I've relisted the plugin.
