### ISSUE TITLE
Book clipping redundancies - remote vs local

### ISSUE THREAD

**Issue by aseyedia** [hadynz/obsidian-kindle-plugin#275]
**Is your feature request related to a problem? Please describe.**

This plug-in is amazing, and honestly has been a big reason why I'm getting back into reading. I feel like I can actually remember the stuff I read now.

One issue that I am having is that I'm getting multiple instances of the same books' clippings in my folder:

![image](https://github.com/hadynz/obsidian-kindle-plugin/assets/43455034/8ee65bda-fe2a-453a-a236-7bfb184da3a1)

I highlight a lot and take a lot of clippings. I also sync onto my phone. 

**Describe the solution you'd like**

I wish there was a way to 

a) identify which books were sync'd via Amazon Cloud and which were sync'd via `My Clippings.txt`.
b) manage clippings based on metadata such as "date last modified" or whether it was sync'd via Cloud or not
c) merge or eliminate redundancies

I'm not familiar with typescript but this could be something I contribute as well. Thanks again for developing this plugin!

**Comment by hadynz** [comment]
The reason why you are seeing multiple instances of a book (with a unique suffix added) is because of conflicts. As you've pointed you, you've imported the same book from two sources. The plugin will not try to merge or resolve any conflicts, but keep them separately.

I suppose what you are asking for is to have more control on how the plugin handles this automatically for you.
