### ISSUE TITLE
Mobile support?

### ISSUE THREAD

**Issue by ryanpcmcquen** [hadynz/obsidian-kindle-plugin#41]
Thanks for this plugin! Your code has helped me quite a bit on my own plugin. Would love to see mobile support, since I need to handle a similar flow in my own plugin. If I figure it out first, I will let you know!

**Comment by hadynz** [comment]
Hey @ryanpcmcquen. I don't know know much yet about Obsidian's mobile architecture and requirements for plugins to work. If you know of any references that can be of help that would really be great.

Currently the plugin has a hard requirement on `electron` (it uses it to open a browser in memory and to screen scrape highlights from Amazon's site). That is the key question that would make or break whether I can implement your request.

**Comment by ryanpcmcquen** [comment]
I _think_ the mobile flow will work with my plugin, but I am waiting for it to get added to really test it:
https://github.com/ryanpcmcquen/obsidian-dropbox-backups

**Comment by hadynz** [comment]
@licat was able to confirm [on discord][1] that Obsidian on mobile does not have electron. This means that this plugin can only work on desktop until a fundamental change to its architecture is made.

Marking this issue as "won't fix".

[1]: https://discord.com/channels/686053708261228577/840286264964022302/848593768504492072

**Comment by ryanpcmcquen** [comment]
In case you are curious, I got the OAuth flow working on mobile in my plugin, I just use the built-in browser with `window.location.assign`.

**Comment by hadynz** [comment]
I see now what you original meant @ryanpcmcquen.

The plugin currently works by screen scraping. So the basic components to be able to do so are:

1. Auth — allow a user to login to their Amazon account. Their session should be accessible for future requests
2. Loading Dom — be able to call a url (after they are logged in) and have access to the DOM in order to scrape its content. This typically needs to have in a transparent way to the user (i.e. they shouldn't be required to see the page loading in front of them)

The best way to date is using electron's `BrowserWindow` object. I'd have to sit down and look at pure JavaScript solutions only. That would be a solution that work cross platform.
