### ISSUE TITLE
Problem with image url

### ISSUE THREAD

**Issue by edward-peters** [hadynz/obsidian-kindle-plugin#56]
Your plug in is one of the most important for me, thanks so much for it.

I have a problem which may have a simple solution. The urls for book cover being pulled in from Amazon have a character which Obsidian recognises as starting italics, and I can’t get the transcluded image url to show up as an image in Preview mode.

Example:  ![[https://m.media-amazon.com/images/I/8116vy-AXCL._SY160.jpg]]

Am I doing something wrong?

I get an error saying the file is not created. And everything after the _ in the file name is in italics, the rest of the section.

**Comment by hadynz** [comment]
This is such an interesting problem that you raise @edward-peters. Could it be because the book is about Trump 😈.

On a more serious note, I think this could be a bug in the Obsidian code editor. I've [asked the question][1] on Obsidian's discord to see what comes back.

[1]: https://discord.com/channels/686053708261228577/694233507500916796/852731337264594944

**Comment by hadynz** [comment]
[Confirmed by @licat](https://discord.com/channels/686053708261228577/694233507500916796/852732748803604491) that this is a known issue with the Obsidian editor. I actually tried it out, and the preview mode doesn't have this problem

**Comment by edward-peters** [comment]
@hadynz It is good of you to take the trouble. I have found what I was doing wrong. Very sorry to have troubled you, and thanks again for your superb plug in. I will buy you a coffee!
