### ISSUE TITLE
Can't log in to account

### ISSUE THREAD

**Issue by tyf2018** [hadynz/obsidian-kindle-plugin#6]
Unable to log in to the account, prompting that we cannot find an account with the email address/mobile number
Looking forward to this problem being resolved, thank you very much
![C_2021 04 27_11 08 27](https://user-images.githubusercontent.com/56342788/116178917-eff18980-a748-11eb-950c-6fd839100d98.jpg)

**Comment by mkasu** [comment]
I think different countries sometimes use separate accounts (E.g., Amazon.co.jp and Amazon.cn use separate accounts which can't login to .com and European domains.) US and EU accounts seem to be shared though. 
I can't use Readwise for example because they only support read.amazon.com and not read.amazon.co.jp.

For this plugin, I'm not sure if it is as simple as changing the backend domain or whether there need to be some API related changes. The Web apps look more or less identical though.

**Comment by hadynz** [comment]
The Obsidian plugin is a wrapper around Amazon's authentication flow. So hearing the error that you are getting, tells me it is one of two issues:

1. The Amazon credentials that you are using are incorrect (unlikely)
2. The login URL that the Obsidian plugin is using (https://www.amazon.com/ap/signin) is not valid for the region that you are in

@tyf2018 can you confirm if you are able to login in https://www.amazon.com/ap/signin? Take note of the URL and any redirection that happens. Let me know how you go on.

**Comment by hadynz** [comment]
@mkasu if you can help provision me a Japanese Amazon account, or share with me temporarily the login credentials of an existing one, I can get this plugin to work for your region.

**Comment by tyf2018** [comment]
> The Obsidian plugin is a wrapper around Amazon's authentication flow. So hearing the error that you are getting, tells me it is one of two issues:
> 
> 1. The Amazon credentials that you are using are incorrect (unlikely)
> 2. The login URL that the Obsidian plugin is using (https://www.amazon.com/ap/signin) is not valid for the region that you are in
> 
> @tyf2018 can you confirm if you are able to login in https://www.amazon.com/ap/signin? Take note of the URL and any redirection that happens. Let me know how you go on.

I cant login in   https://www.amazon.com/ap/signin
![C_2021 04 28_16 01 16](https://user-images.githubusercontent.com/56342788/116368502-fb24e200-a83a-11eb-8c27-115abcbbc5d6.jpg)

**Comment by hadynz** [comment]
What `signin` Amazon url works for your region?

And once you are logged in, can you manually access your notes via `https://read.amazon.com/notebook`?

**Comment by tyf2018** [comment]
> What if you goto this url: `https://read.amazon.com/notebook`.
> 
> Are you able to logout and login to this URL and have access to your books?

I can only log in to my account at this website https://www.amazon.cn/, and all other logins fail

**Comment by hadynz** [comment]
@tyf2018 if you cannot access your Kindle highlights manually yourself via https://read.amazon.com/notebook then this plugin in its current form cannot help as it is simply an automated wrapper. 

I'm working on another feature that I will be releasing shortly that could help you instead. Uploading your highlights from your clippings text file on your Kindle. 

If you are happy with this then you can close this issue.

**Comment by tyf2018** [comment]
> @tyf2018 if you cannot access your Kindle highlights manually yourself via https://read.amazon.com/notebook then this plugin in its current form cannot help as it is simply an automated wrapper.
> 
> I'm working on another feature (#2) that I will be releasing shortly that could help you instead. Uploading your highlights from your clippings text file on your Kindle.
> 
> If you are happy with this then you can close this issue.

Thank you.

**Comment by mkasu** [comment]
I can’t speak for CN but for Japan the url https://read.amazon.co.jp/notebook works the same way as US just with a seperate account system.

I can’t provide my account because I have all kinds of personal data attached. But Amazon.co.jp has English option if you want to create a test account. I can try to debug it too when I have some time.

**Comment by hadynz** [comment]
@mkasu thanks for the insight. 

I'm trying to think of one solution that would work for all Amazom regions. Can you confirm for me if by going to https://read.amazon.com/notebook it automatically redirects you to https://read.amazon.co.jp/notebook were you can login?

If it doesn't. Then the only other solution I can think of is providing you with a drop-down in settings to choose your account region. Choosing Japan would mean the plugins uses a Url scheme that always ends in .co.jp for signing in and browsing notes.

**Comment by mkasu** [comment]
Thanks for the efforts. There's no redirect so I think drop-down is the only option. :(

**Comment by zzdcgg** [comment]
@hadynz Hey - another Kindle account from China.  Had the same issue whey trying to sync with ReadWise.  ReadWise pointed me to 2 alternative solutions: 1. Kindle Device (My Clippings); 2. Kindle Apps (Email).  More details can be found through the line below:

https://help.readwise.io/article/30-how-do-i-import-highlights-from-personal-documents-on-kindle

I understand that you are working on the 1st solution (My Clippings) which is great.  I wonder whether the 2nd option, Kindle Apps (Email), is also feasible.  To me, the 2nd option is much more convenient.

Thanks a million!

**Comment by chuckvtt** [comment]
Since the new update a few days ago, I have not been able to log into my USA Amazon account? And when I try to sign out so that I can log back in, it tells me, "error, could not sign out"

I've tried resetting the plug-in and un-installing and re-installing a few times.

Can you give me any other suggestions on what to try thank you, BTW I LOVE this plug-in!!!
