### ISSUE TITLE
Some books never sync, others get mixed

### ISSUE THREAD

**Issue by jeromg** [hadynz/obsidian-kindle-plugin#98]
Hi there,

I have issues where several books are never synced, with some errors in the console like:
```
Error: File name cannot contain any of the following characters: * " \ / < > : | ?
    at t.checkPath (app.js:1)
    at t.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at app.js:1
    at new Promise (<anonymous>)
    at o (app.js:1)
    at t.createFolder (app.js:1)
    at e.<anonymous> (app.js:1)
    at app.js:1
```
I also realized 2 books got completely mixed: the ASIN of one book, with the title of another one and the comments of both books mixed (this issue is not reproducible unfortunately, after deleting all the files, and resetting the sync, the issue did not reappear).

I guess you'd probably need more debug information though. Is there a way to enable a debug mode?

I suspect this might have something to do with special characters in books' titles. For example, I've noticed that the set of books that never sync starts with a book title that contains a dollar sign, the book is ASIN B07B22BKQH

I've also noticed that some of my books end up being created on disk with illegal file characters like ' (single quote) while for some others, the special character were trimmed.

Let me know if you need more details.

Cheers,

Jerome

**Comment by hadynz** [comment]
I will look up the book name with the ASIN number you provided. 

But if you can share the names of the books that keep crashing the plug-in it would help, as we can guard against them.

**Comment by jeromg** [comment]
Apparently, after a couple of syncs, the two following books get mixed:
  - https://www.amazon.com/dp/B0037Z8SLI "The Checklist Manifesto: How To Get Things Right"
  - https://www.amazon.com/dp/B072JTDBJC "Psychosolutions - 2e édition (Psychothérapie) (French Edition)"

Here is what the file in Obsidian looks like (the YAML frontmatter mentions the 2nd file, the metadata mentions the first one):
```
---
kindle-sync:
  bookId: '16137'
  title: Psychosolutions - 2e édition (Psychothérapie) (French Edition)
  author: Giorgio Nardone and Ivan-Denis Cormier
  asin: B072JTDBJC
  lastAnnotatedDate: '2021-05-15'
  bookImageUrl: 'https://m.media-amazon.com/images/I/7179TAOrFwL._SY160.jpg'
  highlightsCount: 1
---
# The Checklist Manifesto
## Metadata
* Author: [Atul Gawande](https://www.amazon.com/Atul-Gawande/e/B00458K698/ref=dp_byline_cont_ebooks_1)
* ASIN: B0037Z8SLI
* ISBN: 0670084409
* Reference: [[https://www.amazon.com/dp/B0037Z8SLI]]
* [Kindle link](kindle://book?action=open&asin=B0037Z8SLI)

```

The error I mentioned in my first message above only happens when I click on the 'Reference' link in the Metadata section, maybe because this link is formatted as an internal link, not a plain URL:
Here is what I have:
`* Reference: [[https://www.amazon.com/dp/B0037Z8SLI]]` (double brackets, same as internal links)
Here is what I would expect:
`* Reference: https://www.amazon.com/dp/B0037Z8SLI`

Cheers,

Jerome

**Comment by hadynz** [comment]
Can you confirm if the following is a complete list of the distinct issues that you are running into:

> I've also noticed that some of my books end up being created on disk with illegal file characters like ' (single quote) while for some others, the special character were trimmed.

**Issue 1** – Illegal characters in file name
This is most certainly unexpected as the plugin sanitises all file names for Unix and Windows. Can you tell me what the name of the book is? And is this consistently happening — i.e. if you delete and resync, will this issue always take place? 

**Issue 2** – URLs in metadata should not be surrounded by square brackets
> Here is what I have:
> `* Reference: [[https://www.amazon.com/dp/B0037Z8SLI]]` (double brackets, same as internal links)
> Here is what I would expect:
> `* Reference: https://www.amazon.com/dp/B0037Z8SLI`

**Issue 3** – Metadata of two books are mixed up
Can I ask you for some more detail about this:

1. Is this consistently reproducible?
2. Is it always the same two books?
3. Is the metadata for each of the books "swapped"? Or is one book rendering perfectly fine as you would expect, and the other is referring to the wrong metadata?
4. Are the annotations for each book correct?

**Issue 4** – Some of your books are never being synced because of illegal file names
> I have issues where several books are never synced, with some errors in the console like:

Is that still an issue that you are running into? You mentioned this at the start, but didn't refer to this problem again. Can you share the list of books that are failing to be synced?

**Comment by hadynz** [comment]
Closing issue as I haven't heard back if the above issues still persist or answers to my questions. Feel free to reopen again if you get a chance to go through my previous post.
